---
version: "3.8"
services:
  alex-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "7.0"
        NODE_VERSION: "lts/*"
    volumes:
      - ..:/workspace:cached
    # Overrides default command
    command: sleep infinity
  alex-api-mock:
    build:
      context: ../specs
      dockerfile: Dockerfile
    volumes:
      - ../specs:/specs
  alex-nginx:
    image: nginx:latest
    container_name: alex-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - alex-api-mock
volumes:
  postgres_data:
    driver: local

