version: '3.8'
services:
  alex-api:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: '6.0'
        NODE_VERSION: 'lts/*'
    volumes:
      - ..:/workspace:cached
    network_mode: service:alex-db
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  alex-nginx:
    image: nginx:latest
    container_name: alex-nginx
    restart: unless-stopped
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443 
  alex-db:
    image: postgres
    container_name: alex-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  alex-idp:
    image: quay.io/keycloak/keycloak:legacy
    container_name: alex-idp
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: alex-db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd      
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
      PROXY_ADDRESS_FORWARDING: "true"
      REDIRECT_SOCKET: "proxy-https"
      KEYCLOAK_FRONTEND_URL: https://alex.local/auth
    depends_on:
      - alex-db
volumes:
  postgres_data:
      driver: local