openapi: '3.0.3'
info:
  title: ALEX API
  version: 1.0.0
  description: ALEX API consumed by ALEX clients.
servers:
  - url: '{server}/api'
    variables:
      server:
        default: https://alex.test
paths:
  /v1/hc:
    $ref: './resources/hc.yml'
  /v1/accounts:
    $ref: './resources/accounts.yml'
  /v1/accounts/{id}:
    $ref: './resources/account.yml'
  /v1/sponsors:
    $ref: './resources/sponsors.yml'
  /v1/sponsors/{id}:
    $ref: './resources/sponsor.yml'
components:
  schemas:
    $ref: "./schemas/_index.yml"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    $ref: "./parameters/_index.yml"
  responses:
    $ref: './components/responses.yml'
security:
  - bearerAuth: []
